--------------------------------------------------------
--  File created - Tuesday-November-19-2013   
--------------------------------------------------------
REM INSERTING into BETTERU.INGREDIENTS_INGREDIENT
SET DEFINE OFF;
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (21,'Chicken Breast',3,1,4,'oz',112,'g',140,4,0,25);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (26,'Whole Grain Thin Spaghetti',5,3,2,'oz',56,'g',180,2,39,9);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (23,'Egg (Large)',3,1,1,'unit',0,'unknown',70,5,0,6);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (25,'0% Greek Yogurt (Plain)',21,2,227,'g',0,'unknown',140,0,9,23);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (27,'Brown Rice',4,3,0,'c',42,'g',150,1,32,3);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (1,'Zero Carb Vanilla',1,1,2,'scoop',62,'g',210,1,0,50);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (2,'Tilapia Filet',2,1,4,'oz',113,'g',90,1,0,21);
Insert into BETTERU.INGREDIENTS_INGREDIENT (ID,NAME,BRAND_ID,CATEGORY_ID,DEFAULT_SERVING_SIZE,DEFAULT_SERVING_UNIT,ALT_SERVING_SIZE,ALT_SERVING_UNIT,CALORIES,FAT,CARBOHYDRATES,PROTEIN) values (24,'0% Milk',3,2,1,'c',8,'oz',90,0,13,8);
commit;