--------------------------------------------------------
--  File created - Tuesday-November-19-2013   
--------------------------------------------------------
REM INSERTING into BETTERU.MEALS_MEALPART
SET DEFINE OFF;
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (5,6,24,12,1);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (6,6,31,40,1);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (7,6,25,227,0);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (8,6,1,2,0);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (2,2,1,2,0);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (3,2,24,12,1);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (1,1,21,300,1);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (21,21,25,227,0);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (22,21,24,12,1);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (23,21,1,2,0);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (4,3,23,2,0);
Insert into BETTERU.MEALS_MEALPART (ID,MEALID,INGREDIENT_ID,AMOUNT,UNIT) values (24,5,21,200,1);
