CREATE OR REPLACE PROCEDURE RESET_SEQ( PNAME IN VARCHAR2 )
IS
  L_CURR NUMBER;
  L_TOT   NUMBER;
  L_SUB NUMBER;
  L_NEG VARCHAR2(1);
BEGIN
  EXECUTE IMMEDIATE 'SELECT ' || PNAME || '_SQ.NEXTVAL FROM DUAL' INTO L_CURR;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || PNAME || '' INTO L_TOT;
  IF L_CURR >= L_TOT THEN
    L_NEG := '-';
    L_SUB := L_CURR - L_TOT;
  ELSE
    L_NEG := '';
    L_SUB := L_TOT - L_CURR;
  END IF;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || PNAME || '_SQ INCREMENT BY ' || L_NEG || L_SUB || ' MINVALUE 0';
  EXECUTE IMMEDIATE 'SELECT ' || PNAME || '_SQ.NEXTVAL FROM DUAL' INTO L_CURR;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || PNAME || '_SQ INCREMENT BY 1 MINVALUE 0';
  COMMIT;
END;
/


