

CREATE OR REPLACE VIEW INGREDIENT_VIEW AS
  SELECT I.ID,
         I.NAME INGREDIENT_NAME,
         B.NAME BRAND_NAME,
         C.NAME CATEGORY_NAME,
         DEFAULT_SERVING_SIZE,
         DEFAULT_SERVING_UNIT,
         ALT_SERVING_SIZE,
         ALT_SERVING_UNIT,
         CALORIES,
         FAT,
         CARBOHYDRATES,
         PROTEIN
  FROM INGREDIENTS_INGREDIENT I
  INNER JOIN INGREDIENTS_BRAND B ON (I.BRAND_ID = B.ID)
  INNER JOIN INGREDIENTS_CATEGORY C ON (I.CATEGORY_ID = C.ID);

CREATE OR REPLACE VIEW INGREDIENTS_MEALPARTSVIEW AS
  SELECT MEALID, MP.AMOUNT, MP.UNIT, INGREDIENT_NAME, BRAND_NAME, CATEGORY_NAME, CALORIES, FAT, CARBOHYDRATES, PROTEIN, DEFAULT_SERVING_SIZE, DEFAULT_SERVING_UNIT, ALT_SERVING_SIZE, ALT_SERVING_UNIT
  FROM INGREDIENTS_MEALPART MP
  JOIN INGREDIENTS_INGREDIENTVIEW IV
  ON MP.INGREDIENT_ID = IV.ID;

CREATE OR REPLACE VIEW INGREDIENTS_MEALVIEW AS
  SELECT MEALID,
         AMOUNT,
         UNIT,
         INGREDIENT_NAME,
         BRAND_NAME,
         CATEGORY_NAME,
         CALORIES,
         FAT,
         CARBOHYDRATES,
         PROTEIN,
         CASE WHEN UNIT = 0 THEN DEFAULT_SERVING_SIZE 
              ELSE ALT_SERVING_SIZE
              END AS SERVING_SIZE,
         CASE WHEN UNIT = 0 THEN DEFAULT_SERVING_UNIT
              ELSE ALT_SERVING_UNIT
              END AS SERVING_UNIT
  FROM INGREDIENTS_MEALPARTSVIEW
  ORDER BY MEALID;


SELECT * FROM INGREDIENTS_INGREDIENTVIEW;
SELECT * FROM INGREDIENTS_MEALPARTSVIEW;
SELECT * FROM INGREDIENTS_MEALVIEW;
